apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-app
  template:
    metadata:
      labels:
        app: playground-app
    spec:
      containers:
      - image: wil42/playground:v2
        name: playground-app
        ports:
        - containerPort: 8888
